// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-git-rev/c7e57cbea9458d80de99aeb0b7b42bb517693f26/git-rev.d.ts
declare module "~git-rev/git-rev" {
  type StringCallback = (str: string) => void;

  namespace GitRev {
    function short(callback: StringCallback): void;
    function long(callback: StringCallback): void;
    function branch(callback: StringCallback): void;
    function tag(callback: StringCallback): void;
    function log(callback: (log: Array<Array<string>>) => void): void;
  }

  export = GitRev;
}

declare module "git-rev/git-rev" {
  import alias = require("~git-rev/git-rev");
  export = alias;
}

declare module "git-rev" {
  import alias = require("~git-rev/git-rev");
  export = alias;
}